pub const IMPORTANTMD: &str = "# IMPORTANT

*This file is generated by VioletCrystal.*

You're using Pack.generate(None) (or Pack.generate(Some(true))) to generate the pack. The problem is that the generate function generates a new UUID in manifests every time
To remove that weird functionality just code it as
```rust
Pack.generate(Some(false))
```";
